apiVersion: v1
kind: Namespace
metadata:
  name: simplewp

---

apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: simplewp
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "rootpassword"
    - name: MYSQL_DATABASE
      value: "wordpress"
    - name: MYSQL_USER
      value: "wpuser"
    - name: MYSQL_PASSWORD
      value: "wppassword"
    ports:
    - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: simplewp
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None # Utilisation d'un ClusterIP pour simplifier la découverte DNS

---

apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  namespace: simplewp
  labels:
    app: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress:latest
    env:
    - name: WORDPRESS_DB_HOST
      value: "mysql"
    - name: WORDPRESS_DB_USER
      value: "wpuser"
    - name: WORDPRESS_DB_PASSWORD
      value: "wppassword"
    - name: WORDPRESS_DB_NAME
      value: "wordpress"
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: simplewp
spec:
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: simplewp
spec:
  rules:
  - host: wordpress.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80
