apiVersion: v1
kind: Pod
metadata:
  name: api-vol
  labels: 
    app: messages-api-vol
spec:
  containers:
  - name: api
    image: lucj/messages:1.0
    volumeMounts:
    - name: mongo-creds
      mountPath: "/run/secrets"
      readOnly: true
  volumes:
  - name: mongo-creds
    secret:
      secretName: mongo
      items:
      - key: mongo_url
        path: MONGODB_URL
---
apiVersion: v1
kind: Service
metadata:
  name: messages-api-vol
  labels:
    app: messages-api-vol
spec:
  selector:
    app: proxy
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31602