apiVersion: v1
kind: Pod
metadata:
  name: api-env
  labels:
    app: messages-api-env
spec:
  containers:
  - name: api
    image: lucj/messages:1.0
    env:
    - name: MONGODB_URL
      valueFrom:
        secretKeyRef:
          name: mongo
          key: mongo_url
---
apiVersion: v1
kind: Service
metadata:
  name: messages-api-env
  labels:
    app: messages-api-env
spec:
  selector:
    app: proxy
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31601